apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-jenkins-home
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/exports"
