apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume-jenkins-home-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
