apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "nginx:1.9.14"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-jenkins-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "tls-certs"
              mountPath: "/etc/tls"
      volumes:
        - name: "tls-certs"
          secret:
            secretName: "tls-certs"
        - name: "nginx-jenkins-conf"
          configMap:
            name: "nginx-jenkins-conf"
            items:
              - key: "jenkins_proxy.conf"
                path: "jenkins_proxy.conf"
